//
// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: provider/v1/provider.proto

package providerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 1
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "SERVING",
		1: "NOT_SERVING",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"SERVING":     0,
		"NOT_SERVING": 1,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_provider_v1_provider_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_provider_v1_provider_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{7, 0}
}

// Type distinguishes synchronous hooks from asynchronous reactions.
type HookRegistration_Type int32

const (
	HookRegistration_SYNC  HookRegistration_Type = 0
	HookRegistration_ASYNC HookRegistration_Type = 1
)

// Enum value maps for HookRegistration_Type.
var (
	HookRegistration_Type_name = map[int32]string{
		0: "SYNC",
		1: "ASYNC",
	}
	HookRegistration_Type_value = map[string]int32{
		"SYNC":  0,
		"ASYNC": 1,
	}
)

func (x HookRegistration_Type) Enum() *HookRegistration_Type {
	p := new(HookRegistration_Type)
	*p = x
	return p
}

func (x HookRegistration_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HookRegistration_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_provider_v1_provider_proto_enumTypes[1].Descriptor()
}

func (HookRegistration_Type) Type() protoreflect.EnumType {
	return &file_provider_v1_provider_proto_enumTypes[1]
}

func (x HookRegistration_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HookRegistration_Type.Descriptor instead.
func (HookRegistration_Type) EnumDescriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{14, 0}
}

// GetInfoRequest is an empty request for GetInfo.
type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{0}
}

// ProviderInfo describes a provider's metadata.
type ProviderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Features      []string               `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty"`
	Dependencies  []string               `protobuf:"bytes,4,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderInfo) Reset() {
	*x = ProviderInfo{}
	mi := &file_provider_v1_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInfo) ProtoMessage() {}

func (x *ProviderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInfo.ProtoReflect.Descriptor instead.
func (*ProviderInfo) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{1}
}

func (x *ProviderInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProviderInfo) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *ProviderInfo) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

// InitRequest carries core runtime context to the provider.
type InitRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TemporalEndpoint  string                 `protobuf:"bytes,1,opt,name=temporal_endpoint,json=temporalEndpoint,proto3" json:"temporal_endpoint,omitempty"`
	TemporalNamespace string                 `protobuf:"bytes,2,opt,name=temporal_namespace,json=temporalNamespace,proto3" json:"temporal_namespace,omitempty"`
	Config            map[string]string      `protobuf:"bytes,4,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ServiceEndpoints  map[string]string      `protobuf:"bytes,5,rep,name=service_endpoints,json=serviceEndpoints,proto3" json:"service_endpoints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{2}
}

func (x *InitRequest) GetTemporalEndpoint() string {
	if x != nil {
		return x.TemporalEndpoint
	}
	return ""
}

func (x *InitRequest) GetTemporalNamespace() string {
	if x != nil {
		return x.TemporalNamespace
	}
	return ""
}

func (x *InitRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *InitRequest) GetServiceEndpoints() map[string]string {
	if x != nil {
		return x.ServiceEndpoints
	}
	return nil
}

// InitResponse is returned after successful initialization.
type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{3}
}

func (x *InitResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *InitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ShutdownRequest is an empty request for Shutdown.
type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{4}
}

// ShutdownResponse is returned after shutdown completes.
type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{5}
}

// HealthCheckRequest is an empty request for HealthCheck.
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{6}
}

// HealthCheckResponse reports the provider's serving status.
type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=nico.provider.v1.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_SERVING
}

// GetRoutesRequest is an empty request for GetRoutes.
type GetRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoutesRequest) Reset() {
	*x = GetRoutesRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoutesRequest) ProtoMessage() {}

func (x *GetRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoutesRequest.ProtoReflect.Descriptor instead.
func (*GetRoutesRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{8}
}

// Route describes an HTTP endpoint the provider handles.
type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Middlewares   []string               `protobuf:"bytes,3,rep,name=middlewares,proto3" json:"middlewares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_provider_v1_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{9}
}

func (x *Route) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Route) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Route) GetMiddlewares() []string {
	if x != nil {
		return x.Middlewares
	}
	return nil
}

// RouteList is a list of routes.
type RouteList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*Route               `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteList) Reset() {
	*x = RouteList{}
	mi := &file_provider_v1_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteList) ProtoMessage() {}

func (x *RouteList) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteList.ProtoReflect.Descriptor instead.
func (*RouteList) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{10}
}

func (x *RouteList) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

// HTTPRequest represents an inbound HTTP request forwarded to the provider.
type HTTPRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Method      string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path        string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Headers     map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	QueryParams map[string]string      `protobuf:"bytes,4,rep,name=query_params,json=queryParams,proto3" json:"query_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PathParams  map[string]string      `protobuf:"bytes,5,rep,name=path_params,json=pathParams,proto3" json:"path_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body        []byte                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	// Tenant context extracted from the Echo context by the core.
	Org           string   `protobuf:"bytes,7,opt,name=org,proto3" json:"org,omitempty"`
	TenantId      string   `protobuf:"bytes,8,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string   `protobuf:"bytes,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Roles         []string `protobuf:"bytes,10,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPRequest) Reset() {
	*x = HTTPRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPRequest) ProtoMessage() {}

func (x *HTTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPRequest.ProtoReflect.Descriptor instead.
func (*HTTPRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{11}
}

func (x *HTTPRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HTTPRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HTTPRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPRequest) GetQueryParams() map[string]string {
	if x != nil {
		return x.QueryParams
	}
	return nil
}

func (x *HTTPRequest) GetPathParams() map[string]string {
	if x != nil {
		return x.PathParams
	}
	return nil
}

func (x *HTTPRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HTTPRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *HTTPRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *HTTPRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HTTPRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

// HTTPResponse is the provider's HTTP response.
type HTTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPResponse) Reset() {
	*x = HTTPResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPResponse) ProtoMessage() {}

func (x *HTTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPResponse.ProtoReflect.Descriptor instead.
func (*HTTPResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{12}
}

func (x *HTTPResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HTTPResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// GetHookRegistrationsRequest is an empty request for GetHookRegistrations.
type GetHookRegistrationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHookRegistrationsRequest) Reset() {
	*x = GetHookRegistrationsRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHookRegistrationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHookRegistrationsRequest) ProtoMessage() {}

func (x *GetHookRegistrationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHookRegistrationsRequest.ProtoReflect.Descriptor instead.
func (*GetHookRegistrationsRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{13}
}

// HookRegistration describes a hook or reaction the provider wants to register.
type HookRegistration struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Type    HookRegistration_Type  `protobuf:"varint,1,opt,name=type,proto3,enum=nico.provider.v1.HookRegistration_Type" json:"type,omitempty"`
	Feature string                 `protobuf:"bytes,2,opt,name=feature,proto3" json:"feature,omitempty"`
	Event   string                 `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
	// For ASYNC reactions only.
	TargetWorkflow string `protobuf:"bytes,4,opt,name=target_workflow,json=targetWorkflow,proto3" json:"target_workflow,omitempty"`
	SignalName     string `protobuf:"bytes,5,opt,name=signal_name,json=signalName,proto3" json:"signal_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HookRegistration) Reset() {
	*x = HookRegistration{}
	mi := &file_provider_v1_provider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookRegistration) ProtoMessage() {}

func (x *HookRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookRegistration.ProtoReflect.Descriptor instead.
func (*HookRegistration) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{14}
}

func (x *HookRegistration) GetType() HookRegistration_Type {
	if x != nil {
		return x.Type
	}
	return HookRegistration_SYNC
}

func (x *HookRegistration) GetFeature() string {
	if x != nil {
		return x.Feature
	}
	return ""
}

func (x *HookRegistration) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *HookRegistration) GetTargetWorkflow() string {
	if x != nil {
		return x.TargetWorkflow
	}
	return ""
}

func (x *HookRegistration) GetSignalName() string {
	if x != nil {
		return x.SignalName
	}
	return ""
}

// HookRegistrationList is a list of hook registrations.
type HookRegistrationList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registrations []*HookRegistration    `protobuf:"bytes,1,rep,name=registrations,proto3" json:"registrations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookRegistrationList) Reset() {
	*x = HookRegistrationList{}
	mi := &file_provider_v1_provider_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookRegistrationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookRegistrationList) ProtoMessage() {}

func (x *HookRegistrationList) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookRegistrationList.ProtoReflect.Descriptor instead.
func (*HookRegistrationList) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{15}
}

func (x *HookRegistrationList) GetRegistrations() []*HookRegistration {
	if x != nil {
		return x.Registrations
	}
	return nil
}

// HookEvent carries hook invocation data to the provider.
type HookEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feature       string                 `protobuf:"bytes,1,opt,name=feature,proto3" json:"feature,omitempty"`
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookEvent) Reset() {
	*x = HookEvent{}
	mi := &file_provider_v1_provider_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookEvent) ProtoMessage() {}

func (x *HookEvent) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookEvent.ProtoReflect.Descriptor instead.
func (*HookEvent) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{16}
}

func (x *HookEvent) GetFeature() string {
	if x != nil {
		return x.Feature
	}
	return ""
}

func (x *HookEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *HookEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// HookResult is the provider's response to a sync hook invocation.
type HookResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookResult) Reset() {
	*x = HookResult{}
	mi := &file_provider_v1_provider_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookResult) ProtoMessage() {}

func (x *HookResult) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookResult.ProtoReflect.Descriptor instead.
func (*HookResult) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{17}
}

func (x *HookResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HookResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// GetOpenAPIFragmentRequest is an empty request for GetOpenAPIFragment.
type GetOpenAPIFragmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOpenAPIFragmentRequest) Reset() {
	*x = GetOpenAPIFragmentRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOpenAPIFragmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpenAPIFragmentRequest) ProtoMessage() {}

func (x *GetOpenAPIFragmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpenAPIFragmentRequest.ProtoReflect.Descriptor instead.
func (*GetOpenAPIFragmentRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{18}
}

// OpenAPIFragment carries the provider's OpenAPI spec as YAML.
type OpenAPIFragment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpecYaml      []byte                 `protobuf:"bytes,1,opt,name=spec_yaml,json=specYaml,proto3" json:"spec_yaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAPIFragment) Reset() {
	*x = OpenAPIFragment{}
	mi := &file_provider_v1_provider_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAPIFragment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAPIFragment) ProtoMessage() {}

func (x *OpenAPIFragment) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAPIFragment.ProtoReflect.Descriptor instead.
func (*OpenAPIFragment) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{19}
}

func (x *OpenAPIFragment) GetSpecYaml() []byte {
	if x != nil {
		return x.SpecYaml
	}
	return nil
}

var File_provider_v1_provider_proto protoreflect.FileDescriptor

const file_provider_v1_provider_proto_rawDesc = "" +
	"\n" +
	"\x1aprovider/v1/provider.proto\x12\x10nico.provider.v1\"\x10\n" +
	"\x0eGetInfoRequest\"|\n" +
	"\fProviderInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bfeatures\x18\x03 \x03(\tR\bfeatures\x12\"\n" +
	"\fdependencies\x18\x04 \x03(\tR\fdependencies\"\xa4\x03\n" +
	"\vInitRequest\x12+\n" +
	"\x11temporal_endpoint\x18\x01 \x01(\tR\x10temporalEndpoint\x12-\n" +
	"\x12temporal_namespace\x18\x02 \x01(\tR\x11temporalNamespace\x12A\n" +
	"\x06config\x18\x04 \x03(\v2).nico.provider.v1.InitRequest.ConfigEntryR\x06config\x12`\n" +
	"\x11service_endpoints\x18\x05 \x03(\v23.nico.provider.v1.InitRequest.ServiceEndpointsEntryR\x10serviceEndpoints\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aC\n" +
	"\x15ServiceEndpointsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x03\x10\x04R\x0etemporal_queue\">\n" +
	"\fInitResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse\"\x14\n" +
	"\x12HealthCheckRequest\"\x91\x01\n" +
	"\x13HealthCheckResponse\x12K\n" +
	"\x06status\x18\x01 \x01(\x0e23.nico.provider.v1.HealthCheckResponse.ServingStatusR\x06status\"-\n" +
	"\rServingStatus\x12\v\n" +
	"\aSERVING\x10\x00\x12\x0f\n" +
	"\vNOT_SERVING\x10\x01\"\x12\n" +
	"\x10GetRoutesRequest\"U\n" +
	"\x05Route\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12 \n" +
	"\vmiddlewares\x18\x03 \x03(\tR\vmiddlewares\"<\n" +
	"\tRouteList\x12/\n" +
	"\x06routes\x18\x01 \x03(\v2\x17.nico.provider.v1.RouteR\x06routes\"\xcf\x04\n" +
	"\vHTTPRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12D\n" +
	"\aheaders\x18\x03 \x03(\v2*.nico.provider.v1.HTTPRequest.HeadersEntryR\aheaders\x12Q\n" +
	"\fquery_params\x18\x04 \x03(\v2..nico.provider.v1.HTTPRequest.QueryParamsEntryR\vqueryParams\x12N\n" +
	"\vpath_params\x18\x05 \x03(\v2-.nico.provider.v1.HTTPRequest.PathParamsEntryR\n" +
	"pathParams\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\x12\x10\n" +
	"\x03org\x18\a \x01(\tR\x03org\x12\x1b\n" +
	"\ttenant_id\x18\b \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\t \x01(\tR\x06userId\x12\x14\n" +
	"\x05roles\x18\n" +
	" \x03(\tR\x05roles\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10QueryParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fPathParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc6\x01\n" +
	"\fHTTPResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12E\n" +
	"\aheaders\x18\x02 \x03(\v2+.nico.provider.v1.HTTPResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1d\n" +
	"\x1bGetHookRegistrationsRequest\"\xe6\x01\n" +
	"\x10HookRegistration\x12;\n" +
	"\x04type\x18\x01 \x01(\x0e2'.nico.provider.v1.HookRegistration.TypeR\x04type\x12\x18\n" +
	"\afeature\x18\x02 \x01(\tR\afeature\x12\x14\n" +
	"\x05event\x18\x03 \x01(\tR\x05event\x12'\n" +
	"\x0ftarget_workflow\x18\x04 \x01(\tR\x0etargetWorkflow\x12\x1f\n" +
	"\vsignal_name\x18\x05 \x01(\tR\n" +
	"signalName\"\x1b\n" +
	"\x04Type\x12\b\n" +
	"\x04SYNC\x10\x00\x12\t\n" +
	"\x05ASYNC\x10\x01\"`\n" +
	"\x14HookRegistrationList\x12H\n" +
	"\rregistrations\x18\x01 \x03(\v2\".nico.provider.v1.HookRegistrationR\rregistrations\"U\n" +
	"\tHookEvent\x12\x18\n" +
	"\afeature\x18\x01 \x01(\tR\afeature\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"K\n" +
	"\n" +
	"HookResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x1b\n" +
	"\x19GetOpenAPIFragmentRequest\".\n" +
	"\x0fOpenAPIFragment\x12\x1b\n" +
	"\tspec_yaml\x18\x01 \x01(\fR\bspecYaml2\x91\x06\n" +
	"\fNicoProvider\x12K\n" +
	"\aGetInfo\x12 .nico.provider.v1.GetInfoRequest\x1a\x1e.nico.provider.v1.ProviderInfo\x12E\n" +
	"\x04Init\x12\x1d.nico.provider.v1.InitRequest\x1a\x1e.nico.provider.v1.InitResponse\x12Q\n" +
	"\bShutdown\x12!.nico.provider.v1.ShutdownRequest\x1a\".nico.provider.v1.ShutdownResponse\x12Z\n" +
	"\vHealthCheck\x12$.nico.provider.v1.HealthCheckRequest\x1a%.nico.provider.v1.HealthCheckResponse\x12L\n" +
	"\tGetRoutes\x12\".nico.provider.v1.GetRoutesRequest\x1a\x1b.nico.provider.v1.RouteList\x12N\n" +
	"\rHandleRequest\x12\x1d.nico.provider.v1.HTTPRequest\x1a\x1e.nico.provider.v1.HTTPResponse\x12m\n" +
	"\x14GetHookRegistrations\x12-.nico.provider.v1.GetHookRegistrationsRequest\x1a&.nico.provider.v1.HookRegistrationList\x12K\n" +
	"\x0eHandleSyncHook\x12\x1b.nico.provider.v1.HookEvent\x1a\x1c.nico.provider.v1.HookResult\x12d\n" +
	"\x12GetOpenAPIFragment\x12+.nico.provider.v1.GetOpenAPIFragmentRequest\x1a!.nico.provider.v1.OpenAPIFragmentBLZJgithub.com/NVIDIA/infra-controller/provider-api/provider/v1;providerv1b\x06proto3"

var (
	file_provider_v1_provider_proto_rawDescOnce sync.Once
	file_provider_v1_provider_proto_rawDescData []byte
)

func file_provider_v1_provider_proto_rawDescGZIP() []byte {
	file_provider_v1_provider_proto_rawDescOnce.Do(func() {
		file_provider_v1_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provider_v1_provider_proto_rawDesc), len(file_provider_v1_provider_proto_rawDesc)))
	})
	return file_provider_v1_provider_proto_rawDescData
}

var file_provider_v1_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_provider_v1_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_provider_v1_provider_proto_goTypes = []any{
	(HealthCheckResponse_ServingStatus)(0), // 0: nico.provider.v1.HealthCheckResponse.ServingStatus
	(HookRegistration_Type)(0),             // 1: nico.provider.v1.HookRegistration.Type
	(*GetInfoRequest)(nil),                 // 2: nico.provider.v1.GetInfoRequest
	(*ProviderInfo)(nil),                   // 3: nico.provider.v1.ProviderInfo
	(*InitRequest)(nil),                    // 4: nico.provider.v1.InitRequest
	(*InitResponse)(nil),                   // 5: nico.provider.v1.InitResponse
	(*ShutdownRequest)(nil),                // 6: nico.provider.v1.ShutdownRequest
	(*ShutdownResponse)(nil),               // 7: nico.provider.v1.ShutdownResponse
	(*HealthCheckRequest)(nil),             // 8: nico.provider.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 9: nico.provider.v1.HealthCheckResponse
	(*GetRoutesRequest)(nil),               // 10: nico.provider.v1.GetRoutesRequest
	(*Route)(nil),                          // 11: nico.provider.v1.Route
	(*RouteList)(nil),                      // 12: nico.provider.v1.RouteList
	(*HTTPRequest)(nil),                    // 13: nico.provider.v1.HTTPRequest
	(*HTTPResponse)(nil),                   // 14: nico.provider.v1.HTTPResponse
	(*GetHookRegistrationsRequest)(nil),    // 15: nico.provider.v1.GetHookRegistrationsRequest
	(*HookRegistration)(nil),               // 16: nico.provider.v1.HookRegistration
	(*HookRegistrationList)(nil),           // 17: nico.provider.v1.HookRegistrationList
	(*HookEvent)(nil),                      // 18: nico.provider.v1.HookEvent
	(*HookResult)(nil),                     // 19: nico.provider.v1.HookResult
	(*GetOpenAPIFragmentRequest)(nil),      // 20: nico.provider.v1.GetOpenAPIFragmentRequest
	(*OpenAPIFragment)(nil),                // 21: nico.provider.v1.OpenAPIFragment
	nil,                                    // 22: nico.provider.v1.InitRequest.ConfigEntry
	nil,                                    // 23: nico.provider.v1.InitRequest.ServiceEndpointsEntry
	nil,                                    // 24: nico.provider.v1.HTTPRequest.HeadersEntry
	nil,                                    // 25: nico.provider.v1.HTTPRequest.QueryParamsEntry
	nil,                                    // 26: nico.provider.v1.HTTPRequest.PathParamsEntry
	nil,                                    // 27: nico.provider.v1.HTTPResponse.HeadersEntry
}
var file_provider_v1_provider_proto_depIdxs = []int32{
	22, // 0: nico.provider.v1.InitRequest.config:type_name -> nico.provider.v1.InitRequest.ConfigEntry
	23, // 1: nico.provider.v1.InitRequest.service_endpoints:type_name -> nico.provider.v1.InitRequest.ServiceEndpointsEntry
	0,  // 2: nico.provider.v1.HealthCheckResponse.status:type_name -> nico.provider.v1.HealthCheckResponse.ServingStatus
	11, // 3: nico.provider.v1.RouteList.routes:type_name -> nico.provider.v1.Route
	24, // 4: nico.provider.v1.HTTPRequest.headers:type_name -> nico.provider.v1.HTTPRequest.HeadersEntry
	25, // 5: nico.provider.v1.HTTPRequest.query_params:type_name -> nico.provider.v1.HTTPRequest.QueryParamsEntry
	26, // 6: nico.provider.v1.HTTPRequest.path_params:type_name -> nico.provider.v1.HTTPRequest.PathParamsEntry
	27, // 7: nico.provider.v1.HTTPResponse.headers:type_name -> nico.provider.v1.HTTPResponse.HeadersEntry
	1,  // 8: nico.provider.v1.HookRegistration.type:type_name -> nico.provider.v1.HookRegistration.Type
	16, // 9: nico.provider.v1.HookRegistrationList.registrations:type_name -> nico.provider.v1.HookRegistration
	2,  // 10: nico.provider.v1.NicoProvider.GetInfo:input_type -> nico.provider.v1.GetInfoRequest
	4,  // 11: nico.provider.v1.NicoProvider.Init:input_type -> nico.provider.v1.InitRequest
	6,  // 12: nico.provider.v1.NicoProvider.Shutdown:input_type -> nico.provider.v1.ShutdownRequest
	8,  // 13: nico.provider.v1.NicoProvider.HealthCheck:input_type -> nico.provider.v1.HealthCheckRequest
	10, // 14: nico.provider.v1.NicoProvider.GetRoutes:input_type -> nico.provider.v1.GetRoutesRequest
	13, // 15: nico.provider.v1.NicoProvider.HandleRequest:input_type -> nico.provider.v1.HTTPRequest
	15, // 16: nico.provider.v1.NicoProvider.GetHookRegistrations:input_type -> nico.provider.v1.GetHookRegistrationsRequest
	18, // 17: nico.provider.v1.NicoProvider.HandleSyncHook:input_type -> nico.provider.v1.HookEvent
	20, // 18: nico.provider.v1.NicoProvider.GetOpenAPIFragment:input_type -> nico.provider.v1.GetOpenAPIFragmentRequest
	3,  // 19: nico.provider.v1.NicoProvider.GetInfo:output_type -> nico.provider.v1.ProviderInfo
	5,  // 20: nico.provider.v1.NicoProvider.Init:output_type -> nico.provider.v1.InitResponse
	7,  // 21: nico.provider.v1.NicoProvider.Shutdown:output_type -> nico.provider.v1.ShutdownResponse
	9,  // 22: nico.provider.v1.NicoProvider.HealthCheck:output_type -> nico.provider.v1.HealthCheckResponse
	12, // 23: nico.provider.v1.NicoProvider.GetRoutes:output_type -> nico.provider.v1.RouteList
	14, // 24: nico.provider.v1.NicoProvider.HandleRequest:output_type -> nico.provider.v1.HTTPResponse
	17, // 25: nico.provider.v1.NicoProvider.GetHookRegistrations:output_type -> nico.provider.v1.HookRegistrationList
	19, // 26: nico.provider.v1.NicoProvider.HandleSyncHook:output_type -> nico.provider.v1.HookResult
	21, // 27: nico.provider.v1.NicoProvider.GetOpenAPIFragment:output_type -> nico.provider.v1.OpenAPIFragment
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_provider_v1_provider_proto_init() }
func file_provider_v1_provider_proto_init() {
	if File_provider_v1_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provider_v1_provider_proto_rawDesc), len(file_provider_v1_provider_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_provider_v1_provider_proto_goTypes,
		DependencyIndexes: file_provider_v1_provider_proto_depIdxs,
		EnumInfos:         file_provider_v1_provider_proto_enumTypes,
		MessageInfos:      file_provider_v1_provider_proto_msgTypes,
	}.Build()
	File_provider_v1_provider_proto = out.File
	file_provider_v1_provider_proto_goTypes = nil
	file_provider_v1_provider_proto_depIdxs = nil
}
