//
// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: provider/v1/provider.proto

package providerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NicoProvider_GetInfo_FullMethodName              = "/nico.provider.v1.NicoProvider/GetInfo"
	NicoProvider_Init_FullMethodName                 = "/nico.provider.v1.NicoProvider/Init"
	NicoProvider_Shutdown_FullMethodName             = "/nico.provider.v1.NicoProvider/Shutdown"
	NicoProvider_HealthCheck_FullMethodName          = "/nico.provider.v1.NicoProvider/HealthCheck"
	NicoProvider_GetRoutes_FullMethodName            = "/nico.provider.v1.NicoProvider/GetRoutes"
	NicoProvider_HandleRequest_FullMethodName        = "/nico.provider.v1.NicoProvider/HandleRequest"
	NicoProvider_GetHookRegistrations_FullMethodName = "/nico.provider.v1.NicoProvider/GetHookRegistrations"
	NicoProvider_HandleSyncHook_FullMethodName       = "/nico.provider.v1.NicoProvider/HandleSyncHook"
	NicoProvider_GetOpenAPIFragment_FullMethodName   = "/nico.provider.v1.NicoProvider/GetOpenAPIFragment"
	NicoProvider_GetResourceTypes_FullMethodName     = "/nico.provider.v1.NicoProvider/GetResourceTypes"
)

// NicoProviderClient is the client API for NicoProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NicoProvider is the gRPC service that external provider sidecars implement.
type NicoProviderClient interface {
	// GetInfo returns the provider's metadata (name, version, features, dependencies).
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*ProviderInfo, error)
	// Init initializes the provider with core runtime context.
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
	// Shutdown gracefully stops the provider.
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	// HealthCheck verifies the provider is operational.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// GetRoutes returns the list of HTTP routes the provider handles.
	GetRoutes(ctx context.Context, in *GetRoutesRequest, opts ...grpc.CallOption) (*RouteList, error)
	// HandleRequest proxies an HTTP request to the provider.
	HandleRequest(ctx context.Context, in *HTTPRequest, opts ...grpc.CallOption) (*HTTPResponse, error)
	// GetHookRegistrations returns the hooks and reactions this provider wants.
	GetHookRegistrations(ctx context.Context, in *GetHookRegistrationsRequest, opts ...grpc.CallOption) (*HookRegistrationList, error)
	// HandleSyncHook invokes a synchronous hook handler in the provider.
	HandleSyncHook(ctx context.Context, in *HookEvent, opts ...grpc.CallOption) (*HookResult, error)
	// GetOpenAPIFragment returns the provider's OpenAPI spec fragment.
	// Actions declared in GetResourceTypes SHOULD also appear here so that
	// NICo's OpenAPI aggregation and the UI sidebar stay consistent.
	GetOpenAPIFragment(ctx context.Context, in *GetOpenAPIFragmentRequest, opts ...grpc.CallOption) (*OpenAPIFragment, error)
	// GetResourceTypes returns the resource types and actions this provider
	// contributes to NICo's dynamic UI.  NICo calls this once after Init succeeds
	// and caches the result; providers signal changes by restarting.
	// The sidebar renders one nav entry per registered resource type, linking to
	// {api_prefix}/ui/.  The provider is responsible for serving complete HTML
	// pages at those paths via HandleRequest — NICo core does not template them.
	GetResourceTypes(ctx context.Context, in *GetResourceTypesRequest, opts ...grpc.CallOption) (*GetResourceTypesResponse, error)
}

type nicoProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewNicoProviderClient(cc grpc.ClientConnInterface) NicoProviderClient {
	return &nicoProviderClient{cc}
}

func (c *nicoProviderClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*ProviderInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProviderInfo)
	err := c.cc.Invoke(ctx, NicoProvider_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nicoProviderClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, NicoProvider_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nicoProviderClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, NicoProvider_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nicoProviderClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, NicoProvider_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nicoProviderClient) GetRoutes(ctx context.Context, in *GetRoutesRequest, opts ...grpc.CallOption) (*RouteList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteList)
	err := c.cc.Invoke(ctx, NicoProvider_GetRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nicoProviderClient) HandleRequest(ctx context.Context, in *HTTPRequest, opts ...grpc.CallOption) (*HTTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HTTPResponse)
	err := c.cc.Invoke(ctx, NicoProvider_HandleRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nicoProviderClient) GetHookRegistrations(ctx context.Context, in *GetHookRegistrationsRequest, opts ...grpc.CallOption) (*HookRegistrationList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HookRegistrationList)
	err := c.cc.Invoke(ctx, NicoProvider_GetHookRegistrations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nicoProviderClient) HandleSyncHook(ctx context.Context, in *HookEvent, opts ...grpc.CallOption) (*HookResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HookResult)
	err := c.cc.Invoke(ctx, NicoProvider_HandleSyncHook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nicoProviderClient) GetOpenAPIFragment(ctx context.Context, in *GetOpenAPIFragmentRequest, opts ...grpc.CallOption) (*OpenAPIFragment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenAPIFragment)
	err := c.cc.Invoke(ctx, NicoProvider_GetOpenAPIFragment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nicoProviderClient) GetResourceTypes(ctx context.Context, in *GetResourceTypesRequest, opts ...grpc.CallOption) (*GetResourceTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResourceTypesResponse)
	err := c.cc.Invoke(ctx, NicoProvider_GetResourceTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NicoProviderServer is the server API for NicoProvider service.
// All implementations must embed UnimplementedNicoProviderServer
// for forward compatibility.
//
// NicoProvider is the gRPC service that external provider sidecars implement.
type NicoProviderServer interface {
	// GetInfo returns the provider's metadata (name, version, features, dependencies).
	GetInfo(context.Context, *GetInfoRequest) (*ProviderInfo, error)
	// Init initializes the provider with core runtime context.
	Init(context.Context, *InitRequest) (*InitResponse, error)
	// Shutdown gracefully stops the provider.
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	// HealthCheck verifies the provider is operational.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// GetRoutes returns the list of HTTP routes the provider handles.
	GetRoutes(context.Context, *GetRoutesRequest) (*RouteList, error)
	// HandleRequest proxies an HTTP request to the provider.
	HandleRequest(context.Context, *HTTPRequest) (*HTTPResponse, error)
	// GetHookRegistrations returns the hooks and reactions this provider wants.
	GetHookRegistrations(context.Context, *GetHookRegistrationsRequest) (*HookRegistrationList, error)
	// HandleSyncHook invokes a synchronous hook handler in the provider.
	HandleSyncHook(context.Context, *HookEvent) (*HookResult, error)
	// GetOpenAPIFragment returns the provider's OpenAPI spec fragment.
	// Actions declared in GetResourceTypes SHOULD also appear here so that
	// NICo's OpenAPI aggregation and the UI sidebar stay consistent.
	GetOpenAPIFragment(context.Context, *GetOpenAPIFragmentRequest) (*OpenAPIFragment, error)
	// GetResourceTypes returns the resource types and actions this provider
	// contributes to NICo's dynamic UI.  NICo calls this once after Init succeeds
	// and caches the result; providers signal changes by restarting.
	// The sidebar renders one nav entry per registered resource type, linking to
	// {api_prefix}/ui/.  The provider is responsible for serving complete HTML
	// pages at those paths via HandleRequest — NICo core does not template them.
	GetResourceTypes(context.Context, *GetResourceTypesRequest) (*GetResourceTypesResponse, error)
	mustEmbedUnimplementedNicoProviderServer()
}

// UnimplementedNicoProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNicoProviderServer struct{}

func (UnimplementedNicoProviderServer) GetInfo(context.Context, *GetInfoRequest) (*ProviderInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedNicoProviderServer) Init(context.Context, *InitRequest) (*InitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedNicoProviderServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedNicoProviderServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedNicoProviderServer) GetRoutes(context.Context, *GetRoutesRequest) (*RouteList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoutes not implemented")
}
func (UnimplementedNicoProviderServer) HandleRequest(context.Context, *HTTPRequest) (*HTTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleRequest not implemented")
}
func (UnimplementedNicoProviderServer) GetHookRegistrations(context.Context, *GetHookRegistrationsRequest) (*HookRegistrationList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHookRegistrations not implemented")
}
func (UnimplementedNicoProviderServer) HandleSyncHook(context.Context, *HookEvent) (*HookResult, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleSyncHook not implemented")
}
func (UnimplementedNicoProviderServer) GetOpenAPIFragment(context.Context, *GetOpenAPIFragmentRequest) (*OpenAPIFragment, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOpenAPIFragment not implemented")
}
func (UnimplementedNicoProviderServer) GetResourceTypes(context.Context, *GetResourceTypesRequest) (*GetResourceTypesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResourceTypes not implemented")
}
func (UnimplementedNicoProviderServer) mustEmbedUnimplementedNicoProviderServer() {}
func (UnimplementedNicoProviderServer) testEmbeddedByValue()                      {}

// UnsafeNicoProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NicoProviderServer will
// result in compilation errors.
type UnsafeNicoProviderServer interface {
	mustEmbedUnimplementedNicoProviderServer()
}

func RegisterNicoProviderServer(s grpc.ServiceRegistrar, srv NicoProviderServer) {
	// If the following call panics, it indicates UnimplementedNicoProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NicoProvider_ServiceDesc, srv)
}

func _NicoProvider_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NicoProviderServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NicoProvider_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NicoProviderServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NicoProvider_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NicoProviderServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NicoProvider_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NicoProviderServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NicoProvider_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NicoProviderServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NicoProvider_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NicoProviderServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NicoProvider_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NicoProviderServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NicoProvider_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NicoProviderServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NicoProvider_GetRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NicoProviderServer).GetRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NicoProvider_GetRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NicoProviderServer).GetRoutes(ctx, req.(*GetRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NicoProvider_HandleRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HTTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NicoProviderServer).HandleRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NicoProvider_HandleRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NicoProviderServer).HandleRequest(ctx, req.(*HTTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NicoProvider_GetHookRegistrations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHookRegistrationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NicoProviderServer).GetHookRegistrations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NicoProvider_GetHookRegistrations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NicoProviderServer).GetHookRegistrations(ctx, req.(*GetHookRegistrationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NicoProvider_HandleSyncHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HookEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NicoProviderServer).HandleSyncHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NicoProvider_HandleSyncHook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NicoProviderServer).HandleSyncHook(ctx, req.(*HookEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _NicoProvider_GetOpenAPIFragment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOpenAPIFragmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NicoProviderServer).GetOpenAPIFragment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NicoProvider_GetOpenAPIFragment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NicoProviderServer).GetOpenAPIFragment(ctx, req.(*GetOpenAPIFragmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NicoProvider_GetResourceTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourceTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NicoProviderServer).GetResourceTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NicoProvider_GetResourceTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NicoProviderServer).GetResourceTypes(ctx, req.(*GetResourceTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NicoProvider_ServiceDesc is the grpc.ServiceDesc for NicoProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NicoProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nico.provider.v1.NicoProvider",
	HandlerType: (*NicoProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _NicoProvider_GetInfo_Handler,
		},
		{
			MethodName: "Init",
			Handler:    _NicoProvider_Init_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _NicoProvider_Shutdown_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _NicoProvider_HealthCheck_Handler,
		},
		{
			MethodName: "GetRoutes",
			Handler:    _NicoProvider_GetRoutes_Handler,
		},
		{
			MethodName: "HandleRequest",
			Handler:    _NicoProvider_HandleRequest_Handler,
		},
		{
			MethodName: "GetHookRegistrations",
			Handler:    _NicoProvider_GetHookRegistrations_Handler,
		},
		{
			MethodName: "HandleSyncHook",
			Handler:    _NicoProvider_HandleSyncHook_Handler,
		},
		{
			MethodName: "GetOpenAPIFragment",
			Handler:    _NicoProvider_GetOpenAPIFragment_Handler,
		},
		{
			MethodName: "GetResourceTypes",
			Handler:    _NicoProvider_GetResourceTypes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "provider/v1/provider.proto",
}
