//
// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: provider/v1/services.proto

package providerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NicoNetworkingService_GetVpcByID_FullMethodName = "/nico.provider.v1.NicoNetworkingService/GetVpcByID"
	NicoNetworkingService_GetSubnets_FullMethodName = "/nico.provider.v1.NicoNetworkingService/GetSubnets"
)

// NicoNetworkingServiceClient is the client API for NicoNetworkingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NicoNetworkingService exposes networking resource queries for cross-domain
// lookups by external providers.
type NicoNetworkingServiceClient interface {
	// GetVpcByID returns a single VPC by its UUID.
	GetVpcByID(ctx context.Context, in *GetVpcByIDRequest, opts ...grpc.CallOption) (*VpcResponse, error)
	// GetSubnets returns subnets matching the given VPC ID.
	GetSubnets(ctx context.Context, in *GetSubnetsRequest, opts ...grpc.CallOption) (*SubnetListResponse, error)
}

type nicoNetworkingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNicoNetworkingServiceClient(cc grpc.ClientConnInterface) NicoNetworkingServiceClient {
	return &nicoNetworkingServiceClient{cc}
}

func (c *nicoNetworkingServiceClient) GetVpcByID(ctx context.Context, in *GetVpcByIDRequest, opts ...grpc.CallOption) (*VpcResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VpcResponse)
	err := c.cc.Invoke(ctx, NicoNetworkingService_GetVpcByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nicoNetworkingServiceClient) GetSubnets(ctx context.Context, in *GetSubnetsRequest, opts ...grpc.CallOption) (*SubnetListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubnetListResponse)
	err := c.cc.Invoke(ctx, NicoNetworkingService_GetSubnets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NicoNetworkingServiceServer is the server API for NicoNetworkingService service.
// All implementations should embed UnimplementedNicoNetworkingServiceServer
// for forward compatibility.
//
// NicoNetworkingService exposes networking resource queries for cross-domain
// lookups by external providers.
type NicoNetworkingServiceServer interface {
	// GetVpcByID returns a single VPC by its UUID.
	GetVpcByID(context.Context, *GetVpcByIDRequest) (*VpcResponse, error)
	// GetSubnets returns subnets matching the given VPC ID.
	GetSubnets(context.Context, *GetSubnetsRequest) (*SubnetListResponse, error)
}

// UnimplementedNicoNetworkingServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNicoNetworkingServiceServer struct{}

func (UnimplementedNicoNetworkingServiceServer) GetVpcByID(context.Context, *GetVpcByIDRequest) (*VpcResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVpcByID not implemented")
}
func (UnimplementedNicoNetworkingServiceServer) GetSubnets(context.Context, *GetSubnetsRequest) (*SubnetListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubnets not implemented")
}
func (UnimplementedNicoNetworkingServiceServer) testEmbeddedByValue() {}

// UnsafeNicoNetworkingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NicoNetworkingServiceServer will
// result in compilation errors.
type UnsafeNicoNetworkingServiceServer interface {
	mustEmbedUnimplementedNicoNetworkingServiceServer()
}

func RegisterNicoNetworkingServiceServer(s grpc.ServiceRegistrar, srv NicoNetworkingServiceServer) {
	// If the following call panics, it indicates UnimplementedNicoNetworkingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NicoNetworkingService_ServiceDesc, srv)
}

func _NicoNetworkingService_GetVpcByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVpcByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NicoNetworkingServiceServer).GetVpcByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NicoNetworkingService_GetVpcByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NicoNetworkingServiceServer).GetVpcByID(ctx, req.(*GetVpcByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NicoNetworkingService_GetSubnets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubnetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NicoNetworkingServiceServer).GetSubnets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NicoNetworkingService_GetSubnets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NicoNetworkingServiceServer).GetSubnets(ctx, req.(*GetSubnetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NicoNetworkingService_ServiceDesc is the grpc.ServiceDesc for NicoNetworkingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NicoNetworkingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nico.provider.v1.NicoNetworkingService",
	HandlerType: (*NicoNetworkingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVpcByID",
			Handler:    _NicoNetworkingService_GetVpcByID_Handler,
		},
		{
			MethodName: "GetSubnets",
			Handler:    _NicoNetworkingService_GetSubnets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "provider/v1/services.proto",
}

const (
	NicoComputeService_GetInstanceByID_FullMethodName = "/nico.provider.v1.NicoComputeService/GetInstanceByID"
	NicoComputeService_GetMachineByID_FullMethodName  = "/nico.provider.v1.NicoComputeService/GetMachineByID"
)

// NicoComputeServiceClient is the client API for NicoComputeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NicoComputeService exposes compute resource queries for cross-domain
// lookups by external providers.
type NicoComputeServiceClient interface {
	// GetInstanceByID returns a single instance by its UUID.
	GetInstanceByID(ctx context.Context, in *GetInstanceByIDRequest, opts ...grpc.CallOption) (*InstanceResponse, error)
	// GetMachineByID returns a single machine by its string ID.
	GetMachineByID(ctx context.Context, in *GetMachineByIDRequest, opts ...grpc.CallOption) (*MachineResponse, error)
}

type nicoComputeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNicoComputeServiceClient(cc grpc.ClientConnInterface) NicoComputeServiceClient {
	return &nicoComputeServiceClient{cc}
}

func (c *nicoComputeServiceClient) GetInstanceByID(ctx context.Context, in *GetInstanceByIDRequest, opts ...grpc.CallOption) (*InstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceResponse)
	err := c.cc.Invoke(ctx, NicoComputeService_GetInstanceByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nicoComputeServiceClient) GetMachineByID(ctx context.Context, in *GetMachineByIDRequest, opts ...grpc.CallOption) (*MachineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineResponse)
	err := c.cc.Invoke(ctx, NicoComputeService_GetMachineByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NicoComputeServiceServer is the server API for NicoComputeService service.
// All implementations should embed UnimplementedNicoComputeServiceServer
// for forward compatibility.
//
// NicoComputeService exposes compute resource queries for cross-domain
// lookups by external providers.
type NicoComputeServiceServer interface {
	// GetInstanceByID returns a single instance by its UUID.
	GetInstanceByID(context.Context, *GetInstanceByIDRequest) (*InstanceResponse, error)
	// GetMachineByID returns a single machine by its string ID.
	GetMachineByID(context.Context, *GetMachineByIDRequest) (*MachineResponse, error)
}

// UnimplementedNicoComputeServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNicoComputeServiceServer struct{}

func (UnimplementedNicoComputeServiceServer) GetInstanceByID(context.Context, *GetInstanceByIDRequest) (*InstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstanceByID not implemented")
}
func (UnimplementedNicoComputeServiceServer) GetMachineByID(context.Context, *GetMachineByIDRequest) (*MachineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMachineByID not implemented")
}
func (UnimplementedNicoComputeServiceServer) testEmbeddedByValue() {}

// UnsafeNicoComputeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NicoComputeServiceServer will
// result in compilation errors.
type UnsafeNicoComputeServiceServer interface {
	mustEmbedUnimplementedNicoComputeServiceServer()
}

func RegisterNicoComputeServiceServer(s grpc.ServiceRegistrar, srv NicoComputeServiceServer) {
	// If the following call panics, it indicates UnimplementedNicoComputeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NicoComputeService_ServiceDesc, srv)
}

func _NicoComputeService_GetInstanceByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NicoComputeServiceServer).GetInstanceByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NicoComputeService_GetInstanceByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NicoComputeServiceServer).GetInstanceByID(ctx, req.(*GetInstanceByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NicoComputeService_GetMachineByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMachineByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NicoComputeServiceServer).GetMachineByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NicoComputeService_GetMachineByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NicoComputeServiceServer).GetMachineByID(ctx, req.(*GetMachineByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NicoComputeService_ServiceDesc is the grpc.ServiceDesc for NicoComputeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NicoComputeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nico.provider.v1.NicoComputeService",
	HandlerType: (*NicoComputeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInstanceByID",
			Handler:    _NicoComputeService_GetInstanceByID_Handler,
		},
		{
			MethodName: "GetMachineByID",
			Handler:    _NicoComputeService_GetMachineByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "provider/v1/services.proto",
}
