//
// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: provider/v1/services.proto

package providerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVpcByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVpcByIDRequest) Reset() {
	*x = GetVpcByIDRequest{}
	mi := &file_provider_v1_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVpcByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVpcByIDRequest) ProtoMessage() {}

func (x *GetVpcByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVpcByIDRequest.ProtoReflect.Descriptor instead.
func (*GetVpcByIDRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_services_proto_rawDescGZIP(), []int{0}
}

func (x *GetVpcByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type VpcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vpc           *Vpc                   `protobuf:"bytes,1,opt,name=vpc,proto3" json:"vpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VpcResponse) Reset() {
	*x = VpcResponse{}
	mi := &file_provider_v1_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpcResponse) ProtoMessage() {}

func (x *VpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpcResponse.ProtoReflect.Descriptor instead.
func (*VpcResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_services_proto_rawDescGZIP(), []int{1}
}

func (x *VpcResponse) GetVpc() *Vpc {
	if x != nil {
		return x.Vpc
	}
	return nil
}

type Vpc struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Id                        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Org                       string                 `protobuf:"bytes,3,opt,name=org,proto3" json:"org,omitempty"`
	InfrastructureProviderId  string                 `protobuf:"bytes,4,opt,name=infrastructure_provider_id,json=infrastructureProviderId,proto3" json:"infrastructure_provider_id,omitempty"`
	TenantId                  string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SiteId                    string                 `protobuf:"bytes,6,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	Status                    string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	NetworkVirtualizationType string                 `protobuf:"bytes,8,opt,name=network_virtualization_type,json=networkVirtualizationType,proto3" json:"network_virtualization_type,omitempty"`
	RoutingProfile            string                 `protobuf:"bytes,9,opt,name=routing_profile,json=routingProfile,proto3" json:"routing_profile,omitempty"`
	NetworkSecurityGroupId    string                 `protobuf:"bytes,10,opt,name=network_security_group_id,json=networkSecurityGroupId,proto3" json:"network_security_group_id,omitempty"`
	Labels                    map[string]string      `protobuf:"bytes,11,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Vpc) Reset() {
	*x = Vpc{}
	mi := &file_provider_v1_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vpc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vpc) ProtoMessage() {}

func (x *Vpc) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vpc.ProtoReflect.Descriptor instead.
func (*Vpc) Descriptor() ([]byte, []int) {
	return file_provider_v1_services_proto_rawDescGZIP(), []int{2}
}

func (x *Vpc) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vpc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Vpc) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *Vpc) GetInfrastructureProviderId() string {
	if x != nil {
		return x.InfrastructureProviderId
	}
	return ""
}

func (x *Vpc) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Vpc) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *Vpc) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Vpc) GetNetworkVirtualizationType() string {
	if x != nil {
		return x.NetworkVirtualizationType
	}
	return ""
}

func (x *Vpc) GetRoutingProfile() string {
	if x != nil {
		return x.RoutingProfile
	}
	return ""
}

func (x *Vpc) GetNetworkSecurityGroupId() string {
	if x != nil {
		return x.NetworkSecurityGroupId
	}
	return ""
}

func (x *Vpc) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type GetSubnetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VpcId         string                 `protobuf:"bytes,1,opt,name=vpc_id,json=vpcId,proto3" json:"vpc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubnetsRequest) Reset() {
	*x = GetSubnetsRequest{}
	mi := &file_provider_v1_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubnetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubnetsRequest) ProtoMessage() {}

func (x *GetSubnetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubnetsRequest.ProtoReflect.Descriptor instead.
func (*GetSubnetsRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_services_proto_rawDescGZIP(), []int{3}
}

func (x *GetSubnetsRequest) GetVpcId() string {
	if x != nil {
		return x.VpcId
	}
	return ""
}

type SubnetListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subnets       []*Subnet              `protobuf:"bytes,1,rep,name=subnets,proto3" json:"subnets,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubnetListResponse) Reset() {
	*x = SubnetListResponse{}
	mi := &file_provider_v1_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubnetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubnetListResponse) ProtoMessage() {}

func (x *SubnetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubnetListResponse.ProtoReflect.Descriptor instead.
func (*SubnetListResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_services_proto_rawDescGZIP(), []int{4}
}

func (x *SubnetListResponse) GetSubnets() []*Subnet {
	if x != nil {
		return x.Subnets
	}
	return nil
}

func (x *SubnetListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Subnet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Org           string                 `protobuf:"bytes,3,opt,name=org,proto3" json:"org,omitempty"`
	SiteId        string                 `protobuf:"bytes,4,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	VpcId         string                 `protobuf:"bytes,5,opt,name=vpc_id,json=vpcId,proto3" json:"vpc_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Ipv4Prefix    string                 `protobuf:"bytes,7,opt,name=ipv4_prefix,json=ipv4Prefix,proto3" json:"ipv4_prefix,omitempty"`
	Ipv4Gateway   string                 `protobuf:"bytes,8,opt,name=ipv4_gateway,json=ipv4Gateway,proto3" json:"ipv4_gateway,omitempty"`
	Ipv6Prefix    string                 `protobuf:"bytes,9,opt,name=ipv6_prefix,json=ipv6Prefix,proto3" json:"ipv6_prefix,omitempty"`
	Ipv6Gateway   string                 `protobuf:"bytes,10,opt,name=ipv6_gateway,json=ipv6Gateway,proto3" json:"ipv6_gateway,omitempty"`
	PrefixLength  int32                  `protobuf:"varint,11,opt,name=prefix_length,json=prefixLength,proto3" json:"prefix_length,omitempty"`
	Status        string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subnet) Reset() {
	*x = Subnet{}
	mi := &file_provider_v1_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subnet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subnet) ProtoMessage() {}

func (x *Subnet) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subnet.ProtoReflect.Descriptor instead.
func (*Subnet) Descriptor() ([]byte, []int) {
	return file_provider_v1_services_proto_rawDescGZIP(), []int{5}
}

func (x *Subnet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subnet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Subnet) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *Subnet) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *Subnet) GetVpcId() string {
	if x != nil {
		return x.VpcId
	}
	return ""
}

func (x *Subnet) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Subnet) GetIpv4Prefix() string {
	if x != nil {
		return x.Ipv4Prefix
	}
	return ""
}

func (x *Subnet) GetIpv4Gateway() string {
	if x != nil {
		return x.Ipv4Gateway
	}
	return ""
}

func (x *Subnet) GetIpv6Prefix() string {
	if x != nil {
		return x.Ipv6Prefix
	}
	return ""
}

func (x *Subnet) GetIpv6Gateway() string {
	if x != nil {
		return x.Ipv6Gateway
	}
	return ""
}

func (x *Subnet) GetPrefixLength() int32 {
	if x != nil {
		return x.PrefixLength
	}
	return 0
}

func (x *Subnet) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetInstanceByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceByIDRequest) Reset() {
	*x = GetInstanceByIDRequest{}
	mi := &file_provider_v1_services_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceByIDRequest) ProtoMessage() {}

func (x *GetInstanceByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_services_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceByIDRequest.ProtoReflect.Descriptor instead.
func (*GetInstanceByIDRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_services_proto_rawDescGZIP(), []int{6}
}

func (x *GetInstanceByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type InstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceResponse) Reset() {
	*x = InstanceResponse{}
	mi := &file_provider_v1_services_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceResponse) ProtoMessage() {}

func (x *InstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_services_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceResponse.ProtoReflect.Descriptor instead.
func (*InstanceResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_services_proto_rawDescGZIP(), []int{7}
}

func (x *InstanceResponse) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

type Instance struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Id                       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TenantId                 string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	InfrastructureProviderId string                 `protobuf:"bytes,4,opt,name=infrastructure_provider_id,json=infrastructureProviderId,proto3" json:"infrastructure_provider_id,omitempty"`
	SiteId                   string                 `protobuf:"bytes,5,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	VpcId                    string                 `protobuf:"bytes,6,opt,name=vpc_id,json=vpcId,proto3" json:"vpc_id,omitempty"`
	MachineId                string                 `protobuf:"bytes,7,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	Status                   string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Hostname                 string                 `protobuf:"bytes,9,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Labels                   map[string]string      `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_provider_v1_services_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_services_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_provider_v1_services_proto_rawDescGZIP(), []int{8}
}

func (x *Instance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Instance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Instance) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Instance) GetInfrastructureProviderId() string {
	if x != nil {
		return x.InfrastructureProviderId
	}
	return ""
}

func (x *Instance) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *Instance) GetVpcId() string {
	if x != nil {
		return x.VpcId
	}
	return ""
}

func (x *Instance) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *Instance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Instance) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Instance) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type GetMachineByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMachineByIDRequest) Reset() {
	*x = GetMachineByIDRequest{}
	mi := &file_provider_v1_services_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMachineByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMachineByIDRequest) ProtoMessage() {}

func (x *GetMachineByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_services_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMachineByIDRequest.ProtoReflect.Descriptor instead.
func (*GetMachineByIDRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_services_proto_rawDescGZIP(), []int{9}
}

func (x *GetMachineByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MachineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machine       *Machine               `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineResponse) Reset() {
	*x = MachineResponse{}
	mi := &file_provider_v1_services_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineResponse) ProtoMessage() {}

func (x *MachineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_services_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineResponse.ProtoReflect.Descriptor instead.
func (*MachineResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_services_proto_rawDescGZIP(), []int{10}
}

func (x *MachineResponse) GetMachine() *Machine {
	if x != nil {
		return x.Machine
	}
	return nil
}

type Machine struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Id                       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InfrastructureProviderId string                 `protobuf:"bytes,2,opt,name=infrastructure_provider_id,json=infrastructureProviderId,proto3" json:"infrastructure_provider_id,omitempty"`
	SiteId                   string                 `protobuf:"bytes,3,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	InstanceTypeId           string                 `protobuf:"bytes,4,opt,name=instance_type_id,json=instanceTypeId,proto3" json:"instance_type_id,omitempty"`
	Status                   string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	IsAssigned               bool                   `protobuf:"varint,6,opt,name=is_assigned,json=isAssigned,proto3" json:"is_assigned,omitempty"`
	Hostname                 string                 `protobuf:"bytes,7,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Labels                   map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Machine) Reset() {
	*x = Machine{}
	mi := &file_provider_v1_services_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Machine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Machine) ProtoMessage() {}

func (x *Machine) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_services_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Machine.ProtoReflect.Descriptor instead.
func (*Machine) Descriptor() ([]byte, []int) {
	return file_provider_v1_services_proto_rawDescGZIP(), []int{11}
}

func (x *Machine) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Machine) GetInfrastructureProviderId() string {
	if x != nil {
		return x.InfrastructureProviderId
	}
	return ""
}

func (x *Machine) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *Machine) GetInstanceTypeId() string {
	if x != nil {
		return x.InstanceTypeId
	}
	return ""
}

func (x *Machine) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Machine) GetIsAssigned() bool {
	if x != nil {
		return x.IsAssigned
	}
	return false
}

func (x *Machine) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Machine) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_provider_v1_services_proto protoreflect.FileDescriptor

const file_provider_v1_services_proto_rawDesc = "" +
	"\n" +
	"\x1aprovider/v1/services.proto\x12\x10nico.provider.v1\"#\n" +
	"\x11GetVpcByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\vVpcResponse\x12'\n" +
	"\x03vpc\x18\x01 \x01(\v2\x15.nico.provider.v1.VpcR\x03vpc\"\xe1\x03\n" +
	"\x03Vpc\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03org\x18\x03 \x01(\tR\x03org\x12<\n" +
	"\x1ainfrastructure_provider_id\x18\x04 \x01(\tR\x18infrastructureProviderId\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12\x17\n" +
	"\asite_id\x18\x06 \x01(\tR\x06siteId\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12>\n" +
	"\x1bnetwork_virtualization_type\x18\b \x01(\tR\x19networkVirtualizationType\x12'\n" +
	"\x0frouting_profile\x18\t \x01(\tR\x0eroutingProfile\x129\n" +
	"\x19network_security_group_id\x18\n" +
	" \x01(\tR\x16networkSecurityGroupId\x129\n" +
	"\x06labels\x18\v \x03(\v2!.nico.provider.v1.Vpc.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"*\n" +
	"\x11GetSubnetsRequest\x12\x15\n" +
	"\x06vpc_id\x18\x01 \x01(\tR\x05vpcId\"^\n" +
	"\x12SubnetListResponse\x122\n" +
	"\asubnets\x18\x01 \x03(\v2\x18.nico.provider.v1.SubnetR\asubnets\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xd0\x02\n" +
	"\x06Subnet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03org\x18\x03 \x01(\tR\x03org\x12\x17\n" +
	"\asite_id\x18\x04 \x01(\tR\x06siteId\x12\x15\n" +
	"\x06vpc_id\x18\x05 \x01(\tR\x05vpcId\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\x12\x1f\n" +
	"\vipv4_prefix\x18\a \x01(\tR\n" +
	"ipv4Prefix\x12!\n" +
	"\fipv4_gateway\x18\b \x01(\tR\vipv4Gateway\x12\x1f\n" +
	"\vipv6_prefix\x18\t \x01(\tR\n" +
	"ipv6Prefix\x12!\n" +
	"\fipv6_gateway\x18\n" +
	" \x01(\tR\vipv6Gateway\x12#\n" +
	"\rprefix_length\x18\v \x01(\x05R\fprefixLength\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\"(\n" +
	"\x16GetInstanceByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x10InstanceResponse\x126\n" +
	"\binstance\x18\x01 \x01(\v2\x1a.nico.provider.v1.InstanceR\binstance\"\x87\x03\n" +
	"\bInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12<\n" +
	"\x1ainfrastructure_provider_id\x18\x04 \x01(\tR\x18infrastructureProviderId\x12\x17\n" +
	"\asite_id\x18\x05 \x01(\tR\x06siteId\x12\x15\n" +
	"\x06vpc_id\x18\x06 \x01(\tR\x05vpcId\x12\x1d\n" +
	"\n" +
	"machine_id\x18\a \x01(\tR\tmachineId\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1a\n" +
	"\bhostname\x18\t \x01(\tR\bhostname\x12>\n" +
	"\x06labels\x18\n" +
	" \x03(\v2&.nico.provider.v1.Instance.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"'\n" +
	"\x15GetMachineByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x0fMachineResponse\x123\n" +
	"\amachine\x18\x01 \x01(\v2\x19.nico.provider.v1.MachineR\amachine\"\xe9\x02\n" +
	"\aMachine\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12<\n" +
	"\x1ainfrastructure_provider_id\x18\x02 \x01(\tR\x18infrastructureProviderId\x12\x17\n" +
	"\asite_id\x18\x03 \x01(\tR\x06siteId\x12(\n" +
	"\x10instance_type_id\x18\x04 \x01(\tR\x0einstanceTypeId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1f\n" +
	"\vis_assigned\x18\x06 \x01(\bR\n" +
	"isAssigned\x12\x1a\n" +
	"\bhostname\x18\a \x01(\tR\bhostname\x12=\n" +
	"\x06labels\x18\b \x03(\v2%.nico.provider.v1.Machine.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xc2\x01\n" +
	"\x15NicoNetworkingService\x12P\n" +
	"\n" +
	"GetVpcByID\x12#.nico.provider.v1.GetVpcByIDRequest\x1a\x1d.nico.provider.v1.VpcResponse\x12W\n" +
	"\n" +
	"GetSubnets\x12#.nico.provider.v1.GetSubnetsRequest\x1a$.nico.provider.v1.SubnetListResponse2\xd3\x01\n" +
	"\x12NicoComputeService\x12_\n" +
	"\x0fGetInstanceByID\x12(.nico.provider.v1.GetInstanceByIDRequest\x1a\".nico.provider.v1.InstanceResponse\x12\\\n" +
	"\x0eGetMachineByID\x12'.nico.provider.v1.GetMachineByIDRequest\x1a!.nico.provider.v1.MachineResponseBLZJgithub.com/NVIDIA/infra-controller/provider-api/provider/v1;providerv1b\x06proto3"

var (
	file_provider_v1_services_proto_rawDescOnce sync.Once
	file_provider_v1_services_proto_rawDescData []byte
)

func file_provider_v1_services_proto_rawDescGZIP() []byte {
	file_provider_v1_services_proto_rawDescOnce.Do(func() {
		file_provider_v1_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provider_v1_services_proto_rawDesc), len(file_provider_v1_services_proto_rawDesc)))
	})
	return file_provider_v1_services_proto_rawDescData
}

var file_provider_v1_services_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_provider_v1_services_proto_goTypes = []any{
	(*GetVpcByIDRequest)(nil),      // 0: nico.provider.v1.GetVpcByIDRequest
	(*VpcResponse)(nil),            // 1: nico.provider.v1.VpcResponse
	(*Vpc)(nil),                    // 2: nico.provider.v1.Vpc
	(*GetSubnetsRequest)(nil),      // 3: nico.provider.v1.GetSubnetsRequest
	(*SubnetListResponse)(nil),     // 4: nico.provider.v1.SubnetListResponse
	(*Subnet)(nil),                 // 5: nico.provider.v1.Subnet
	(*GetInstanceByIDRequest)(nil), // 6: nico.provider.v1.GetInstanceByIDRequest
	(*InstanceResponse)(nil),       // 7: nico.provider.v1.InstanceResponse
	(*Instance)(nil),               // 8: nico.provider.v1.Instance
	(*GetMachineByIDRequest)(nil),  // 9: nico.provider.v1.GetMachineByIDRequest
	(*MachineResponse)(nil),        // 10: nico.provider.v1.MachineResponse
	(*Machine)(nil),                // 11: nico.provider.v1.Machine
	nil,                            // 12: nico.provider.v1.Vpc.LabelsEntry
	nil,                            // 13: nico.provider.v1.Instance.LabelsEntry
	nil,                            // 14: nico.provider.v1.Machine.LabelsEntry
}
var file_provider_v1_services_proto_depIdxs = []int32{
	2,  // 0: nico.provider.v1.VpcResponse.vpc:type_name -> nico.provider.v1.Vpc
	12, // 1: nico.provider.v1.Vpc.labels:type_name -> nico.provider.v1.Vpc.LabelsEntry
	5,  // 2: nico.provider.v1.SubnetListResponse.subnets:type_name -> nico.provider.v1.Subnet
	8,  // 3: nico.provider.v1.InstanceResponse.instance:type_name -> nico.provider.v1.Instance
	13, // 4: nico.provider.v1.Instance.labels:type_name -> nico.provider.v1.Instance.LabelsEntry
	11, // 5: nico.provider.v1.MachineResponse.machine:type_name -> nico.provider.v1.Machine
	14, // 6: nico.provider.v1.Machine.labels:type_name -> nico.provider.v1.Machine.LabelsEntry
	0,  // 7: nico.provider.v1.NicoNetworkingService.GetVpcByID:input_type -> nico.provider.v1.GetVpcByIDRequest
	3,  // 8: nico.provider.v1.NicoNetworkingService.GetSubnets:input_type -> nico.provider.v1.GetSubnetsRequest
	6,  // 9: nico.provider.v1.NicoComputeService.GetInstanceByID:input_type -> nico.provider.v1.GetInstanceByIDRequest
	9,  // 10: nico.provider.v1.NicoComputeService.GetMachineByID:input_type -> nico.provider.v1.GetMachineByIDRequest
	1,  // 11: nico.provider.v1.NicoNetworkingService.GetVpcByID:output_type -> nico.provider.v1.VpcResponse
	4,  // 12: nico.provider.v1.NicoNetworkingService.GetSubnets:output_type -> nico.provider.v1.SubnetListResponse
	7,  // 13: nico.provider.v1.NicoComputeService.GetInstanceByID:output_type -> nico.provider.v1.InstanceResponse
	10, // 14: nico.provider.v1.NicoComputeService.GetMachineByID:output_type -> nico.provider.v1.MachineResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_provider_v1_services_proto_init() }
func file_provider_v1_services_proto_init() {
	if File_provider_v1_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provider_v1_services_proto_rawDesc), len(file_provider_v1_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_provider_v1_services_proto_goTypes,
		DependencyIndexes: file_provider_v1_services_proto_depIdxs,
		MessageInfos:      file_provider_v1_services_proto_msgTypes,
	}.Build()
	File_provider_v1_services_proto = out.File
	file_provider_v1_services_proto_goTypes = nil
	file_provider_v1_services_proto_depIdxs = nil
}
