# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nico-provisioner-metal3.name" . }}
  namespace: {{ include "nico-provisioner-metal3.namespace" . }}
  labels:
    {{- include "nico-provisioner-metal3.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "nico-provisioner-metal3.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
